"""deleted is default field in portofolio table

Revision ID: 383db1ccde73
Revises: b43fb468eb21
Create Date: 2025-12-24 22:24:15.627963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '383db1ccde73'
down_revision: Union[str, Sequence[str], None] = 'b43fb468eb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portofolio_accounts', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portofolio_accounts', sa.Column('is_default', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
