"""delete mutation table

Revision ID: d63243853a0a
Revises: 383db1ccde73
Create Date: 2026-01-21 12:34:06.499677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd63243853a0a'
down_revision: Union[str, Sequence[str], None] = '383db1ccde73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mutations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutations',
    sa.Column('mutation_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('account_number', mysql.VARCHAR(collation='utf8mb4_general_ci', length=30), nullable=True),
    sa.Column('transaction_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mutation_type', mysql.ENUM('Debit', 'Kredit'), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['account_number'], ['portofolio_accounts.account_number'], name=op.f('mutations_ibfk_1')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], name=op.f('mutations_ibfk_2')),
    sa.PrimaryKeyConstraint('mutation_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
